import numpy as np
from .DiscreteD import DiscreteD
from .GaussD import GaussD
from .MarkovChain import MarkovChain

class HMM:
    """
    HMM - class for Hidden Markov Models, representing
    statistical properties of random sequences.
    Each sample in the sequence is a scalar or vector, with fixed DataSize.
    
    Several HMM objects may be collected in a single multidimensional array.
    
    A HMM represents a random sequence(X1,X2,....Xt,...),
    where each element Xt can be a scalar or column vector.
    The statistical dependence along the (time) sequence is described
    entirely by a discrete Markov chain.
    
    A HMM consists of two sub-objects:
    1: a State Sequence Generator of type MarkovChain
    2: an array of output probability distributions, one for each state
    
    All states must have the same class of output distribution,
    such as GaussD, GaussMixD, or DiscreteD, etc.,
    and the set of distributions is represented by an object array of that class,
    although this is NOT required by general HMM theory.
    
    All output distributions must have identical DataSize property values.
    
    Any HMM output sequence X(t) is determined by a hidden state sequence S(t)
    generated by an internal Markov chain.
    
    The array of output probability distributions, with one element for each state,
    determines the conditional probability (density) P[X(t) | S(t)].
    Given S(t), each X(t) is independent of all other X(:).
    
    
    References:
    Leijon, A. (20xx) Pattern Recognition. KTH, Stockholm.
    Rabiner, L. R. (1989) A tutorial on hidden Markov models
    	and selected applications in speech recognition.
    	Proc IEEE 77, 257-286.
    
    """
    def __init__(self, mc, distributions):

        self.stateGen:MarkovChain = mc
        self.outputDistr : list[GaussD] = distributions

        self.nStates = mc.nStates
        self.dataSize = distributions[0].dataSize
    
    def observationProb(self, x):
        """
        x= matrix or row vector with output data samples
        pX= matrix with output probabilities
        pX(i,j)= P[X(t)=x(t) | S(t)=i]
        """
        pX = np.zeros((len(x), self.nStates))
        for i in range(len(x)):
            for j in range(self.nStates):
                pX[i,j] = self.outputDistr[j].prob(x[i])
        return pX
    
    def rand(self, nSamples):
        """
        [X,S]=rand(self,nSamples); generates a random sequence of data
        from a given Hidden Markov Model.
        
        Input:
        nSamples=  maximum no of output samples (scalars or column vectors)
        
        Result:
        X= matrix or row vector with output data samples
        S= row vector with corresponding integer state values
          obtained from the self.StateGen component.
          nS= length(S) == size(X,2)= number of output samples.
          If the StateGen can generate infinite-duration sequences,
              nS == nSamples
          If the StateGen is a finite-duration MarkovChain,
              nS <= nSamples
        """
        
        S = self.stateGen.rand(nSamples)
        X = np.zeros((self.dataSize, len(S)))
        
        for i in range(len(S)):
            X[:, i] = self.outputDistr[S[i]].rand(1).flatten()
        
        return X, S
    
    def viterbi(self,x):
        pX = self.observationProb(x)
        return self.stateGen.viterbi(pX)

    def train(self, x:np.ndarray , nIter=10, threshold = 0.1, debug=False):
        """
        Train the HMM using the Baum-Welch algorithm.
        
        Input:
        x= matrix or row vector with output data samples
        nIter= number of iterations for training
        
        Result:
        self= trained HMM object
        """
        # Iterate for nIter times
        loglike = - np.inf
        for _ in range(nIter):
            pX = self.observationProb(x)
            # E-step: calculate expected values
            a_hat, c = self.stateGen.forward(pX)
            b_hat = self.stateGen.backward(c,pX)
            # M-step: update parameters
            gamma = np.zeros((len(x), self.nStates))
            for i in range(len(x)):
                for j in range(self.nStates):
                    gamma[i,j] = a_hat[i,j] * b_hat[i,j] * c[i]

            #update initial state probabilities
            q_new = np.zeros(self.nStates)
            for j in range(self.nStates):
                q_new[j] = np.sum(gamma[:,j]) / np.sum(gamma)
            self.stateGen.q = q_new
            if debug:
                print("q:", self.stateGen.q)
            
            #update transition probabilities
            A_new = np.zeros((self.nStates, self.nStates))
            xi = np.zeros((self.nStates, self.nStates, len(x)-1))
            for i in range(self.nStates):
                for j in range(self.nStates):
                    for t in range(len(x)-1):
                        xi[i,j,t] = a_hat[t,i] * self.stateGen.A[i,j] * b_hat[t+1,j] * pX[t+1,j]
            xi_ij = np.zeros((self.nStates, self.nStates))
            for i in range(self.nStates):
                for j in range(self.nStates):
                    xi_ij[i,j] = np.sum(xi[i,j,:])
            for i in range(self.nStates):
                for j in range(self.nStates):
                    A_new[i,j] = xi_ij[i,j] / np.sum(xi_ij[i,:])

            self.stateGen.A = A_new
            if debug:
                print("A:", self.stateGen.A)

            
            #update output distributions
            mu_new = np.zeros((self.nStates, self.dataSize))
            
            for i in range(self.nStates):
                gamma_i = np.sum(gamma[:,i])
                for t in range(len(x)):
                    mu_new[i,:] += gamma[t,i] * x[t]
                mu_new[i,:] /= gamma_i
                self.outputDistr[i].means = mu_new[i,:]
                if debug:
                    print(f"mu:{i+1}", self.outputDistr[i].means)
            
            cov_new = np.zeros((self.nStates, self.dataSize, self.dataSize))
            for i in range(self.nStates):
                gamma_i = np.sum(gamma[:,i])
                for t in range(len(x)):
                    cov_new[i,:,:] += gamma[t,i] * np.outer(x[t]-mu_new[i,:], x[t]-mu_new[i,:])
                cov_new[i,:,:] /= gamma_i
                self.outputDistr[i].cov = cov_new[i,:,:]
                if debug:
                    print(f"cov:{i+1}", self.outputDistr[i].cov)
            loglike_old = loglike
            loglike = np.sum(np.log(c))
            if np.abs(loglike - loglike_old) < threshold:
                break
            print(f"Iter {_} : log-likelihood:", loglike)

    def stateEntropyRate(self):
        pass

    def setStationary(self):
        pass

    def log_like(self,x):
        pX = np.zeros((len(x), self.nStates))
        for i in range(len(x)):
            for j in range(self.nStates):
                pX[i,j] = self.outputDistr[j].prob(x[i]) 
        a_hat, c = self.stateGen.forward(pX)
        return np.sum(np.log(c))

    def adaptStart(self):
        pass

    def adaptSet(self):
        pass

    def adaptAccum(self):
        pass